name: learnease
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  android_intent_plus:
  #State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_screenutil: ^5.9.3

  carousel_slider: ^5.0.0

  cached_network_image: ^3.3.0

  #Notification Related
  flutter_local_notifications: ^16.2.0


  #Json
  freezed: ^2.0.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #VideoPlayer
  better_player:
    git:
      url: https://github.com/Syed-Waleed-Shah/betterplayer.git
      ref: flutter-3.22.0-support

  #Remote Server Related
  dio: ^5.4.0

  #other
  equatable: ^2.0.5
  #firebase related
  firebase_core: ^2.8.0
#  firebase_messaging: ^14.3.0
  #Form Related
  formz: ^0.6.1
  flutter_widget_from_html: ^0.8.5
  #Theme Related
  font_awesome_flutter: ^10.3.0
  flutter_rating_bar: ^4.0.1
  flutter_switch: ^0.3.2
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1

  #Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Intl
  intl:

  image_picker: ^1.0.2

  path: ^1.8.2

  #progress
  percent_indicator: ^4.2.3
  #Local Storage Related
  path_provider: ^2.0.15
  permission_handler: ^9.0.2

  rating_summary: ^1.0.2+1
  relative_time: ^5.0.0
  shimmer: ^3.0.0
  #Syncfusion
  syncfusion_flutter_sliders: ^20.3.61
  syncfusion_flutter_core: ^20.3.61
  #ThrottleApi
  stream_transform: ^2.1.0
  #ID Generator
  uuid: ^3.0.7

  uni_links: ^0.5.1
  url_launcher: ^6.1.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1
  get: ^4.6.6
  iconsax: ^0.0.8



dependency_overrides:
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.1
  json_serializable: ^6.6.2
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
